/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageDigestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRecord"
      | "owner"
      | "recordCount"
      | "recordDigest"
      | "records"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DigestRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDigest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
}

export namespace DigestRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    hash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, hash: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageDigest extends BaseContract {
  connect(runner?: ContractRunner | null): MessageDigest;
  waitForDeployment(): Promise<this>;

  interface: MessageDigestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [id: BigNumberish],
    [[string, bigint, string]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordCount: TypedContractMethod<[], [bigint], "view">;

  recordDigest: TypedContractMethod<[_hash: BytesLike], [bigint], "nonpayable">;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        hash: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[string, bigint, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDigest"
  ): TypedContractMethod<[_hash: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        hash: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DigestRecorded"
  ): TypedContractEvent<
    DigestRecordedEvent.InputTuple,
    DigestRecordedEvent.OutputTuple,
    DigestRecordedEvent.OutputObject
  >;

  filters: {
    "DigestRecorded(uint256,bytes32,uint256)": TypedContractEvent<
      DigestRecordedEvent.InputTuple,
      DigestRecordedEvent.OutputTuple,
      DigestRecordedEvent.OutputObject
    >;
    DigestRecorded: TypedContractEvent<
      DigestRecordedEvent.InputTuple,
      DigestRecordedEvent.OutputTuple,
      DigestRecordedEvent.OutputObject
    >;
  };
}
